FROM daveearley/hi.events-all-in-one

ARG VITE_API_URL_CLIENT
ARG VITE_API_URL_SERVER
ARG VITE_FRONTEND_URL
ARG VITE_STRIPE_PUBLISHABLE_KEY

ENV VITE_API_URL_CLIENT=$VITE_API_URL_CLIENT \
    VITE_API_URL_SERVER=$VITE_API_URL_SERVER \
    VITE_FRONTEND_URL=$VITE_FRONTEND_URL \
    VITE_STRIPE_PUBLISHABLE_KEY=$VITE_STRIPE_PUBLISHABLE_KEY

COPY setEnv.sh /setEnv.sh
RUN chmod +x /setEnv.sh
RUN /setEnv.sh