services:
  - type: web
    name: hi-events
    plan: free
    autoDeploy: false
    runtime: docker
    repo: https://github.com/HiEventsDev/hi.events-render.com.git
    envVars:
      - key: PORT
        value: 80
      - key: DATABASE_URL
        fromDatabase:
          name: hi-events-db
          property: connectionString
      - key: APP_KEY
        generateValue: true
      - key: JWT_SECRET
        generateValue: true
databases:
  - name: hi-events-db
    plan: free