#!/bin/sh

export VITE_API_URL_CLIENT=$RENDER_EXTERNAL_URL/api
export VITE_API_URL_SERVER=http://localhost:80/api
export VITE_FRONTEND_URL=$RENDER_EXTERNAL_URL
export VITE_STRIPE_PUBLISHABLE_KEY=$STRIPE_PUBLISHABLE_KEY

exec /startup.sh
